src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 *  @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $used_year;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $purchase_price;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $sale_price;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     */
    private $category;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;



    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getUsedYear(): ?int
    {
        return $this->used_year;
    }

    public function setUsedYear(?int $used_year): self
    {
        $this->used_year = $used_year;

        return $this;
    }

    public function getPurchasePrice(): ?string
    {
        return $this->purchase_price;
    }

    public function setPurchasePrice(?string $purchase_price): self
    {
        $this->purchase_price = $purchase_price;

        return $this;
    }

    public function getSalePrice(): ?string
    {
        return $this->sale_price;
    }

    public function setSalePrice(?string $sale_price): self
    {
        $this->sale_price = $sale_price;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }
    public function getStatus(): ?string
    {
        return $this->adress;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }
    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }


    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function __toString() {
        return $this->title;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use phpDocumentor\Reflection\Type;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category',EntityType::class,[
                'class' =>Category::class,
                'choice_label' =>'title',
            ])
            ->add('title')
            ->add('keywords')
            ->add('description')
            ->add('image',FileType::class,[
                'label'=> 'Main Image',
                'mapped'=>false,
                'required'=>false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' =>[
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image File',
                    ])
                ],

            ])
            ->add('used_year')
            ->add('purchase_price')
            ->add('sale_price')
            ->add('email')
            ->add('phone')
            ->add('adress')
            ->add('status',ChoiceType::class,[
                'choices'=>[
                    'True'=>'True',
                    'False'=>'False'],
            ])
            ->add('created_at')
            ->add('updated_at')
            ->add('detail',CKEditorType::class,array(
                'config' => array (
                    'uiColor'=> '#ffffff',
                    //...
                ),
            ));

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'csrf_protection'=>false,
        ]);
    }
}

src/Controller/Admin/ProductController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use phpDocumentor\Reflection\File;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="admin_product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('admin/product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_product_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            //************file upload************
            /** @var file $file */
            $file=$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName().'.'. $file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );

                }catch (FileException $e){

                }
                $product->setImage($fileName);
            }
            //******************* file upload***************
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('admin_product_index');
        }

        return $this->render('admin/product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('admin/product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**@var file $file*/
            $file=$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName().'.'. $file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );

                }catch (FileException $e){

                }
                $product->setImage($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_product_index');
        }

        return $this->render('admin/product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        //md5()reduces the similarity to the file names generated by
        //uniqid(),which is based on timestamps
        return md5(uniqid());
    }



    /**
     * @Route("/{id}", name="admin_product_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_product_index');
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\Product1Type;
use App\Repository\ProductRepository;
use phpDocumentor\Reflection\File;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/product")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="user_product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        $user=$this->getUser(); //Get login user data
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findBy(['userid'=>$user->getId()]),
        ]);
    }

    /**
     * @Route("/new", name="user_product_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $product = new Product();
        $form = $this->createForm(Product1Type::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //************file upload************
            /** @var file $file */
            $file=$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName().'.'. $file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName
                    );

                }catch (FileException $e){

                }
                $product->setImage($fileName);
            }
            //******************* file upload***************

            $user=$this->getUser(); //Get login user data
            $product->setUserid($user->getId());
            $product->setStatus("New");

            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('user_product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        //md5()reduces the similarity to the file names generated by
        //uniqid(),which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/{id}", name="user_product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {

        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(Product1Type::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /**@var file $file*/
            $file=$form['image']->getData();
            if($file){
                $fileName=$this->generateUniqueFileName().'.'. $file->guessExtension();
                try{
                    $file->move(
                        $this->getParameter('images_directory'),
                        $fileName

                    );

                }catch (FileException $e){

                }
                $product->setImage($fileName);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_product_index');
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_product_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_product_index');
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('user_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <div class="col mb-2">
        <br><button class="btn btn-danger">Delete</button>
    </div>
</form>

templates/product/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Profile {% endblock %}

{% block body %}

    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"> {{ app.user.name }} Profile </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Shop Page  -->
    <div class="shop-box-inner">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left">
                    <div class="product-categori">

                        {{ include('user/usermenu.html.twig') }}

                    </div>
                </div>

                <div class="col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right">
                    <div class="right-product-box">
                        <h1>User Product Edit</h1>
                        <div class="row product-categorie-box">
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                                    <div class="row">

                                        {{ include('admin/product/_form.html.twig', {'button_label': 'Update'}) }}

                                    </div>
                                    <div class="col-md-2">
                                    <a href="{{ path('user_product_index') }}"class="mb-xs mt-xs mr-xs btn btn-primary">back to list</a>
                                    </div>
                                    <div class="col-md-2">
                                    {{ include('admin/product/_delete_form.html.twig') }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





{% endblock %}

templates/product/index.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Profile {% endblock %}

{% block body %}

    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"> {{ app.user.name }} Profile </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Shop Page  -->
    <div class="shop-box-inner">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left">
                    <div class="product-categori">

                        {{ include('user/usermenu.html.twig') }}

                    </div>
                </div>

                <div class="col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right">
                    <div class="right-product-box">
                        <h1>User Product List</h1>
                        <div class="row product-categorie-box">
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                                    <div class="row">

                                        <div class="col-md-2">
                                            <a href="{{ path('user_product_new') }}" class="btn btn-block btn-success">Create New</a>

                                        </div><br><br>
                                        <table class="table table-bordered">
                                            <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>Title</th>
                                                <th>Keywords</th>
                                                <th>Description</th>
                                                <th>Image</th>
                                                <th>Used_year</th>
                                                <th>Purchase_price</th>
                                                <th>Sale_price</th>
                                                <th>Gallery</th>
                                                <th>status</th>
                                                <th>actions</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for product in products %}
                                                <tr>
                                                    <td>{{ product.id }}</td>
                                                    <td>{{ product.title }}</td>
                                                    <td>{{ product.keywords }}</td>
                                                    <td>{{ product.description }}</td>
                                                    <td><img src="{{ asset('uploads/images/'  ~ product.image) }}" height="40" ></td>
                                                    <td>{{ product.usedYear }}</td>
                                                    <td>{{ product.purchasePrice }}</td>
                                                    <td>{{ product.salePrice }}</td>

                                                    <td>
                                                        <a href="javascript:openWin('{{ path('admin_image_new',{'id':product.id }) }}','','toolbar=no,location=no,directories=0,status=no,top=50,left=100,menuBar=no,scrollBars=yes,resizable=no,width=900,height=700');">
                                                            <img src="{{ asset('assets/admin/img') }}/gallery.jpg" height="40">
                                                        </a>
                                                    </td>
                                                    <td>{{ product.status }}</td>
                                                    <td>
                                                        <a href="{{ path('user_product_show', {'id': product.id}) }}"class="btn btn-block btn-info">Show</a>

                                                        <a href="{{ path('user_product_edit', {'id': product.id}) }}"class="btn btn-block btn-info">Edit</a>
                                                        {{ include('admin/product/_delete_form.html.twig') }}
                                                    </td>

                                                </tr>
                                            {% else %}
                                                <tr>
                                                    <td colspan="14">no records found</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>


                                    </div>




                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





{% endblock %}

templates/product/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %} {{ app.user.name }} Profile {% endblock %}

{% block body %}
    <SCRIPT language="JavaScript" type="text/javascript">
        function openWin(windowURL,windowName,windowFeatures){  window.open(windowURL,windowName,windowFeatures);}
    </SCRIPT>
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Home</a></li>
                        <li class="breadcrumb-item active"> {{ app.user.name }} Profile </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start Shop Page  -->
    <div class="shop-box-inner">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left">
                    <div class="product-categori">

                        {{ include('user/usermenu.html.twig') }}

                    </div>
                </div>

                <div class="col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right">
                    <div class="right-product-box">
                        <h1>User Product Detail</h1>
                        <div class="row product-categorie-box">
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                                    <div class="row">


                                        <table class="table">
                                            <tbody>
                                            <tr>
                                                <th>Id</th>
                                                <td>{{ product.id }}</td>
                                            </tr>
                                            <tr>
                                                <th>Title</th>
                                                <td>{{ product.title }}</td>
                                            </tr>
                                            <tr>
                                                <th>Keywords</th>
                                                <td>{{ product.keywords }}</td>
                                            </tr>
                                            <tr>
                                                <th>Description</th>
                                                <td>{{ product.description }}</td>
                                            </tr>
                                            <tr>
                                                <th>Image</th>
                                                <td><img src="{{ asset('uploads/images/'  ~ product.image) }}" height="100" ></td>
                                            </tr>
                                            <tr>
                                                <th>Used_year</th>
                                                <td>{{ product.usedYear }}</td>
                                            </tr>
                                            <tr>
                                                <th>Purchase_price</th>
                                                <td>{{ product.purchasePrice }}</td>
                                            </tr>
                                            <tr>
                                                <th>Sale_price</th>
                                                <td>{{ product.salePrice }}</td>
                                            </tr>
                                            <tr>
                                                <th>Email</th>
                                                <td>{{ product.email }}</td>
                                            </tr>
                                            <tr>
                                                <th>Phone</th>
                                                <td>{{ product.phone }}</td>
                                            </tr>
                                            <tr>
                                                <th>Adress</th>
                                                <td>{{ product.adress }}</td>
                                            </tr>
                                            <tr>
                                                <th>Status</th>
                                                <td>{{ product.status }}</td>
                                            </tr>
                                            <tr>
                                                <th>Created_at</th>
                                                <td>{{ product.createdAt ? product.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Updated_at</th>
                                                <td>{{ product.updatedAt ? product.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                            </tr>
                                            </tbody>
                                        </table>


                                    </div>
                                    <a href="{{ path('user_product_index') }}"class="mb-xs mt-xs mr-xs btn btn-primary">back to list</a>



                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





{% endblock %}